<a href="https://colab.research.google.com/github/erYash15/ML-and-AI/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy 

Array and Matrix

Index and Slicing

Operation

In [ ]:
import numpy as np

In [ ]:
mylist = [1,2,3]

In [ ]:
np.array(mylist)

array([1, 2, 3])

In [ ]:
nested_list = [[1,2],[3,4]]

In [ ]:
np.array(nested_list)

array([[1, 2],
       [3, 4]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros(3) #floating points

array([0., 0., 0.])

In [ ]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.linspace(0,10,3) #include end value ... evenly spaced points

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [ ]:
np.eye(5) # identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#random arrays

In [ ]:
np.random.rand(2)

array([0.84949606, 0.65398231])

In [ ]:
np.random.rand(3,4)

array([[0.60159654, 0.52265364, 0.85363784, 0.22817283],
       [0.47287218, 0.33466403, 0.36557368, 0.37324085],
       [0.06836684, 0.41385542, 0.89990435, 0.19221155]])

In [ ]:
np.random.randn(5,5) #mean = 0 #sd = 1

array([[-0.15498764, -0.42512008, -0.07512948, -0.10931844, -0.57964108],
       [ 0.34079811,  0.72885293, -0.36319035, -0.30155065, -0.7572202 ],
       [ 0.3604108 , -0.81027799,  0.06180029, -0.76765103, -1.78183832],
       [ 0.16663289,  0.67233155, -0.39910274,  1.78842454,  0.2280037 ],
       [-0.86481716,  0.82283283, -0.83160134, -0.92239988, -0.44825724]])

In [ ]:
np.random.randint(1,100)

38

In [ ]:
np.random.randint(1,100,10)

array([74, 49, 52, 16, 98, 53, 66, 33,  5, 26])

In [ ]:
np.random.randint(1,100,(2,3))

array([[72, 66, 61],
       [94, 39, 23]])

In [ ]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [ ]:
arr = np.arange(25)

In [ ]:
ranarr = np.random.randint(0,100,10)

In [ ]:
arr.shape

(25,)

In [ ]:
arr_re = arr.reshape(5,5)

In [ ]:
arr_re.reshape(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr.max()

99

In [ ]:
ranarr.argmax()

0

In [ ]:
ranarr

array([99, 23,  2, 21, 52,  1, 87, 29, 37,  1])

In [ ]:
ranarr.min()

1

In [ ]:
ranarr.argmin()

5

x-------------------xxxxxxxxxxxxxxxx------------------xxxxxxxxxxxxxxxxxxxxxxx-------------------------

In [ ]:
import numpy as np
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[1:3] = 100

In [ ]:
arr

array([  0, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
arr2 = arr

In [ ]:
arr[1] = 5

In [ ]:
arr2

array([  0,   5, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
arr3 = arr.copy()

In [ ]:
arr3

array([  0,   5, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
arr[1] = 55

In [ ]:
arr

array([  0,  55, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
arr3

array([  0,   5, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr_2d.shape

(3, 3)

In [ ]:
arr_2d[1,1]

5

In [ ]:
arr_2d[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
arr_2d[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
arr = np.arange(1,11)

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
if (arr > 4).all():
  print("True")

In [ ]:
if (arr > 4).any():
  print("True")

True


In [ ]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

---------xxxxxxxxx-----------------xxxxxxxxxxx------------------

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0,10)

In [ ]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr-5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr / arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
np.nan

nan

In [ ]:
np.inf

inf

In [ ]:
1/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
1/0

ZeroDivisionError: ignored

In [ ]:
arr ** (0.5)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
arr.min()

0

In [ ]:
arr.max()

9

In [ ]:
arr.sum()

45

In [ ]:
arr.mean()

4.5

In [ ]:
arr.std()

2.8722813232690143

In [ ]:
arr.var()

8.25

In [ ]:
arr.var() ** (1/2)

2.8722813232690143

In [ ]:
arr2d = np.arange(25).reshape((5,5))

In [ ]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr2d.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [ ]:
arr2d.sum(axis = 1)

array([ 10,  35,  60,  85, 110])

In [ ]:
arr2d.sum()